steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '--build-arg'
      - 'VITE_API_BASE_URL=https://mangalam-backend-7nyxicd5wq-el.a.run.app'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=AIzaSyCMsWD6oKqPspd8NevIttBBvtm5m5yVZhg'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=mangalam-71d5c.firebaseapp.com'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=mangalam-71d5c'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=mangalam-71d5c.firebasestorage.app'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=231084447820'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=1:231084447820:web:fb050723f1738e1d9fbce9'
      - '-t'
      - 'asia-south1-docker.pkg.dev/mangalam-486305/mangalam-repo/mangalam-frontend:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/mangalam-486305/mangalam-repo/mangalam-frontend:latest']
images:
  - 'asia-south1-docker.pkg.dev/mangalam-486305/mangalam-repo/mangalam-frontend:latest'
